### PR TITLE
fix: Issue/509 vote posts on profile

### LINKED ISSUE #509: Unable to Upvote/Downvote posts from Profile
When visiting a profile, go to the Posts for that user, try to upvote/downvote posts they have made.

### PR DESCRIPTION
**Pull request by Felix-Staud**
Fixes #509 

- Fixes being able to up and down vote posts in profile posts/profile saved posts.
- Gets rid of `UserProfileSavedPosts.tsx` by determining with. a boolean flag in `UserProfilePosts.tsx` if it is the saved on. 
- Fixes an import issue with `navigate` (as discussed in #509)
- adjusts the empty message shown when it is the saved posts

### CODE REVIEW

**Comment by gkasdorf** [comment]
Thanks, I'll look it over here in a few.

File: src/components/screens/UserProfile/UserPostsScreen.tsx [hunk 1]
```diff
@@ -10,21 +11,51 @@ import LoadingErrorView from "../../common/Loading/LoadingErrorView";
...
-  route: any;
+  route: Route<"UserPostsScreen", IRouteParams>;
 }
 
 function UserPostsScreen({ route }: IProps) {
   const profile = useProfile(false, route?.params?.fullUsername);
 
   const theme = useTheme();
 
+  const isSavedPosts = React.useMemo(
```
Comment (gkasdorf) [inline src/components/screens/UserProfile/UserPostsScreen.tsx:28]: isSavedPosts doesn't ever change so we shouldn't need to use a memo here.

File: src/components/screens/UserProfile/UserPostsScreen.tsx [hunk 2]
```diff
@@ -10,21 +11,51 @@ import LoadingErrorView from "../../common/Loading/LoadingErrorView";
...
+    () => route?.params?.isSavedPosts || false,
+    [route]
+  );
+
+  const posts = React.useMemo(
```
Comment (gkasdorf) [inline src/components/screens/UserProfile/UserPostsScreen.tsx:33]: I think we want to re-render whenever posts changes because whenever upvoting/downvoting or saving posts, we update the posts state.

File: src/components/screens/UserProfile/UserPostsScreen.tsx (hunk 1 above)
Comment (Felix-Staud) [reply src/components/screens/UserProfile/UserPostsScreen.tsx:28]: Depends. Assuming the screen component is cached this value will react to any change in it route. This might be the case when you are switching from profile posts to saved profile posts. Not entirely sure though. I did just kinda use it as shorthand that is reactive to changes of route

File: src/components/screens/UserProfile/UserPostsScreen.tsx (hunk 2 above)
Comment (Felix-Staud) [reply src/components/screens/UserProfile/UserPostsScreen.tsx:33]: This will cause an update to the posts object anyway which is a dependency of the hook thus forcing it to update its own return state.

**Comment by gkasdorf** [comment]
So oddly, it seems that regardless of whether I remove *all* dependencies from the memos (aside from posts, that needs to have either profile.posts or profile.savedPosts), we still end up with 7 renders over 5 without any memos. I won't pretend to know what might cause that. Curious if you know.

Regardless, I *think* (?) we should just remove the memos all together as well as the useCallback. For the record, the useCallback doesn't appear to change anything as far as scrolling goes. I thought it might cause issues with FlashList, but doesn't appear to.

Let me know what you think. I can just remove the memos and commit if that's what we think.

Also, nice on the typing of params. I actually couldn't find the correct way to do that, good to know and I'll definitely be updating some stuff in the repo based off that.

**Review by gkasdorf — APPROVED** [review]
Per conversation, removed the memos. Thank you.

**Comment by gkasdorf** [comment]
Per the conversation, just removed the memos. Thanks!
